config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations'
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :forums
  resources :games
  resources :informations
  resources :supports
  resources :contacts, except: [:update, :edit]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :newest_information_id

  def index
    render locals: {
      newest_informations: Information.order("created_at DESC").first(4).compact,
      newest_games: Game.published.order("created_at DESC").first(6).compact,
      slider_images: SliderImage.all
    }
  end

  private

  def newest_information_id(game_id)
    return unless newest_information(game_id).present?
    newest_information(game_id)
  end

  def newest_information(game_id)
    Information.where(game_id: game_id).order("created_at DESC").first
  end

end

app/views/home/_games.html.haml
%section.games.m-top50
  .main-row
    %h2.section-title
      gry
    .decoration-right
      =image_tag('home_page_games_bar.png')
  .games-container.bg-section
    .row
      .games-nav
        %ul
          %li
            =link_to 'POPULARNE', games_path
          %li
            =link_to 'NOWE', games_path
    .row
      -newest_games.each do |game|
        .col-sm-4
          .box-3
            .box-img
              - if current_user.present?
                =link_to image_tag(game.image.image, size: "170"), game_path([game.id])
              - else
                =image_tag(game.image.image, size: "170")
            .box-text
              .col-sm-6.news-box
                .title
                  %h3
                    =game.title
              .col-sm-6.news-box.icons.grey-icons
                = image_tag('icons/icon_home.png', class: 'home-image')
                = image_tag('icons/icon_play.png', class: 'play-image')
              .col-sm-6.news-box.icons.white-icons
                = link_to image_tag('icons/icon_home_white.png', class: 'home-image'), informations_path(information_id: newest_information_id(game.id))
                = link_to image_tag('icons/icon_play_white.png', class: 'play-image'), game_path([game.id])
    .row
      .col-sm-12.more-games
        = link_to 'WIECEJ', games_path

app/views/home/_jumbo.html.haml
%section.jumbo
  %script{:src => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", :type => "text/javascript"}
  .main-slider
    -slider_images.each do |slider_image|
      .slide
        .slide-img
          =image_tag(slider_image.image)
        .slide-text
          %p.m-bot25
            =image_tag('Academy_of_heroes.png')
          .cta-btn
            -if current_user.present?
              %a{href: games_path}
                Zagraj!
            -else
              = link_to "Zagraj!", "#sign_up", "data-toggle" => "modal", class: 'btn-registration'

app/views/home/_news.html.haml
%section.news.m-top50
  .main-row
    .decoration.left
      =image_tag('home_page_games_bar.png')
    %h2.section-title
      newsy
    %span.news-archive
      = link_to 'archiwum', informations_path
  .container
    .row-with-boxes
      -newest_informations.each do |information|
        =link_to informations_path(information_id: information.id) do
          .box-4
            .box-img
              =image_tag(information.information_image.image,size: "166")
            .box-text
              .title
                %h3
                  =information.game.title
              .date
                %p
                  =information.created_at.strftime("%Y-%m-%d")
              .promo-text
                %p
                  =information.short_information

app/views/home/index.html.haml
= render 'jumbo', slider_images: slider_images
= render 'news', newest_informations: newest_informations
= render 'games', newest_games: newest_games