config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations'
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :forums
  resources :games
  resources :informations
  resources :supports
  resources :contacts, except: [:update, :edit]
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

    def index
    end

    def show
      render :show, locals: { contact: contact }
    end

    def new
      render :new, locals: { contact_form: ContactFormObject.new() }
    end

    def create
      contact_form = ContactFormObject.new(contact_params)
      begin
        Contacts::Create.new(contact_form).process
        render :info
      rescue Contacts::Create::ValidationError
        render :new, locals: { contact_form: contact_form }
      end
    end

    def destroy
      if contact.destroy
        flash[:notice] = 'Wykasowano wiadomość'
      else
        flash[:alert] = 'Nie udało się skasować wiadomości'
      end
    end

    private

    def contact_params
      params.require(:contact).permit(:content, :title, :sender, :email)
    end

    def contact
      @contact ||= Contact.find(params[:id])
    end
end

app/views/contacts/_info.html.haml
%button.close{"data-dismiss" => "modal"}
  ×
%p Wysłano prośbe o kontakt. Spodziewaj się odpowiedzi na przestrzeni najbliższych dni. Pozdrawiamy!

app/views/contacts/_new.html.haml
= simple_form_for contact_form, as: :contact, url: contacts_path, remote: true do |f|
  %button.close{"data-dismiss" => "modal"}
    ×
  .form-row
    = f.input :sender, placeholder: 'Imię lub nick', label: false, input_html: { class: 'reuglar-input'}
    = f.input :email, placeholder: 'E-mail', label: false, input_html: { class: 'reuglar-input'}
  .form-row
    = f.input :title, placeholder: 'Temat', label: false, input_html: { class: 'wider-input'}
  .form-row
    = f.input :content, placeholder: 'Treść wiadomości...', label: false, as: :text, input_html: { class: 'big-input'}
  .form-actions
    = f.submit 'Wyślij', class: 'btn btn-modal send'

app/views/contacts/info.js.erb
$("#modal-custom").modal();
$("#modal-custom .modal-header h4").html('<%= j "Prośba o kontakt wysłana" %>');
$("#modal-custom .modal-body").html('<%= j render "info" %>');

app/views/contacts/new.js.erb
$("#modal-custom").modal();
$("#modal-custom .modal-header h4").html('<%= j "Skontaktuj się z nami!" %>');
$("#modal-custom .modal-body").html('<%= j render "new", contact_form: contact_form %>');