config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations'
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :forums
  resources :games
  resources :informations
  resources :supports
  resources :contacts, except: [:update, :edit]
end

app/models/information.rb
class Information < ApplicationRecord
  has_one :information_image
  belongs_to :game
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  def index
    render locals: {
      informations: Information.order('created_at DESC'),
      information: active_information
    }
  end

  def show
    render locals: {
      information: Information.find(params[:id])
    }
  end

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private
  def information_params
    params.require(:information).permit(:title, :short_information, :long_information)
  end

  def active_information
     params.has_key?(:information_id) ? Information.find(params[:information_id]) : Information.last
  end

end

app/views/informations/_information.html.haml
.news
  .row
    =image_tag(information.information_image.image)
  .row.date-row
    = information.created_at.strftime('%d.%m.%Y')
  .row.game-title-row
    =link_to information.game.title, game_path(information.game.id), class: 'link'
  .row.news-title-row
    = information.title
  .row.news-body
    = information.long_information.html_safe

app/views/informations/_list.html.haml
.news-list
  - informations.each do |information|
    = link_to information_path(information.id), remote: true do
      .row.row-info
        .box-img{:id => "#{information.id}"}
          .img-g
            = image_tag(information.information_image.image, size: "176x100")
          .date-row
            %p= information.created_at.strftime('%d.%m.%Y')
          .game-title-row
            %p= information.title
          .news-body
            %p= information.short_information

app/views/informations/index.html.haml
.row
  .col-sm-12
    %section.m-top50
      .main-row
        .decoration-news.left
          =image_tag('bg_gradient.png')
        %h2.information-title
          newsy-archiwum
%section.row-news
  .container
    = render 'information', information: information
    = render 'list', informations: informations
%section.games.m-top50
  .main-row
    .play
      =link_to game_path(information.game.id) do
        %p ZAGRAJ
    .home
      =link_to root_path do
        = image_tag('icons/icon_home_white.png')
    .decoration.right
      =image_tag('bg_gradient.png')

app/views/informations/show.js.erb
$(".news").html('<%= j render 'information', information: information %>');