config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations'
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :forums
  resources :games
  resources :informations
  resources :supports
  resources :contacts, except: [:update, :edit]
end

app/views/layouts/_footer.html.haml
%footer
  .container
    .logo
      %a{:href => ""}
        =image_tag('logo_black.png')
    .row
      .copyright
        %span
          /.Copyright © Copyright 1996-2018 Company Co. All rights reserved
          .Copyright
            =Footer.first.content

app/views/layouts/_header.html.haml
%header{'data-turbolinks' => "false"}
  .container
    .logo
      %a{:href => root_path}
        = image_tag('logo.png')
    %nav.main-nav
      %ul
        %li
          = link_to 'START', root_path
        %li
          = link_to 'GRY', games_path
        %li
          = link_to 'NEWSY', informations_path
        %li
          = link_to 'FORUM', forums_path
        %li
          = link_to 'KONTAKT', new_contact_path, remote: true
        %li.social-media
          %a{:href => ""}
            %i.fab.fa-facebook

  .decor_bg
    .dbg=image_tag('header_bg.png')
    .add-nav
      - unless current_user.present?
        %ul
          %li
            = link_to "Zaloguj się", "#sign_in", "data-toggle" => "modal", class: 'btn-login'
          %li
            = link_to "Rejestracja", "#sign_up", "data-toggle" => "modal", class: 'btn-registration'
          %li
            = image_tag('flaga.png')
      - else
        .row
          .col-sm-3.first-column
            .row.nick-row
              = current_user.nick
            .row.img-row
              .h-img
                = image_tag('icons/icon_alert.png')
              .h-img
                = image_tag('icons/icon_avatar.png')
          .col-sm-9.second-column
            .row
              .main-avatar-img
                = link_to "#edit_up", "data-toggle" => "modal", class: 'btn-edit' do
                  = image_tag current_user.avatar.url
              .h-img
                = link_to destroy_user_session_path, method: :delete do
                  = image_tag('icons/icon_logout.png')
              .flag
                = image_tag('flaga.png')

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Webgames
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    //* SLICK SLIDER **/
    %link{:href => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", :rel => "stylesheet", :type => "text/css"}/
    / Add the slick-theme.css if you want default styling
    %link{:href => "//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css", :rel => "stylesheet", :type => "text/css"}/
    //* END SLICK SLIDER **/
    %link{:href => "https://use.fontawesome.com/releases/v5.0.8/css/all.css", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', :media => "all"
    = javascript_include_tag 'application'
  %body{ "data-js-class-name" => js_class_name }
    #modal-custom.modal.fade
      .modal-dialog
        .modal-content
          .modal-header
            %h4.modal-title
          .modal-body
    = render 'layouts/messages'
    = render 'devise/sessions/new'
    = render 'devise/registrations/edit'
    = render 'devise/registrations/new'
    = render 'devise/passwords/new'
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'